repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.4
      hooks:
          - id: ruff

    - repo: https://github.com/pycqa/isort
      rev: 6.0.0
      hooks:
          - id: isort
            name: isort (python)

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
                - flake8-builtins
                - flake8-coding
                - flake8-polyfill
                - flake8-quotes
                - flake8-string-format
                - flake8-print
                - flake8-bandit

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.14.1"
      hooks:
          - id: mypy
            additional_dependencies: [types-requests, types-PyYAML, types-toml, types-cryptography]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8"
      hooks:
          - id: prettier
            types_or: [css, javascript]
            exclude: "(.*/vendor/.*|.*/js/.*|.*/tinymce/.*|.*/css/main\\.css$)"
