repos:
    - repo: https://github.com/pycqa/isort
      rev: 6.0.0
      hooks:
          - id: isort
            name: isort (python)

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
                - flake8-builtins
                - flake8-coding
                - flake8-polyfill
                - flake8-quotes
                - flake8-string-format
                - flake8-print
                - flake8-bandit
                - flake8-unused-arguments

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.14.1"
      hooks:
          - id: mypy
            additional_dependencies: [types-requests, types-PyYAML, types-toml]

    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
            additional_dependencies: [toml]
